#!/usr/bin/env python3
"""Generate 2026-08-09 raw channel dump for #mowgo from persisted fetch output."""
import json, datetime

SRC = "/tmp/hermes-results/call_00_wS8Kb7P4GVzZYvJoNiyr9970.txt"
CUTOFF = datetime.datetime(2026, 8, 8, 2, 0, 0, tzinfo=datetime.timezone.utc)
OUT = "/opt/data/mowgo/vault/2026-08-09_channel-mowgo-raw.md"

with open(SRC) as f:
    data = json.load(f)

msgs = sorted(data["messages"], key=lambda m: m["timestamp"])
new = [m for m in msgs if datetime.datetime.fromisoformat(m["timestamp"]) > CUTOFF]

# Count content-bearing vs footer-only (footer = "To stop or manage this job..." only)
def is_footer(m):
    c = m["content"].strip()
    return c.startswith("To stop or manage this job")

content_new = [m for m in new if not is_footer(m)]
footer_new = [m for m in new if is_footer(m)]

lines = []
lines.append("# 🌱 mowgo — Raw Channel Dump")
lines.append(f"**2026-08-09 02:00 UTC | 100 messages fetched ({len(new)} new since last sync; {len(content_new)} with content + {len(footer_new)} footer-only trailer(s))**")
lines.append("")
lines.append("## Most Recent Activity (New since Aug 08 02:00 UTC sync)")
lines.append("")

# Group consecutive messages by minute for headers
i = 0
while i < len(new):
    m = new[i]
    ts = datetime.datetime.fromisoformat(m["timestamp"])
    # gather the group: same author + same minute
    group = [m]
    j = i + 1
    while j < len(new):
        tsj = datetime.datetime.fromisoformat(new[j]["timestamp"])
        if new[j]["author"]["id"] == m["author"]["id"] and abs((tsj - ts).total_seconds()) < 90:
            group.append(new[j])
            j += 1
        else:
            break
    # Build header label
    t0 = datetime.datetime.fromisoformat(group[0]["timestamp"])
    t1 = datetime.datetime.fromisoformat(group[-1]["timestamp"])
    ts_label = t0.strftime("%b %d, %H:%M")
    auth = group[0]["author"]["username"]
    # First content-bearing message gives the title: prefer a markdown header line
    first_content = next((g for g in group if not is_footer(g)), group[0])
    title = None
    for ln in first_content["content"].splitlines():
        s = ln.strip()
        if s.startswith("# ") and "MowGo BI" in s:
            title = s.lstrip("# ").strip()
            break
    if not title:
        for ln in first_content["content"].splitlines():
            s = ln.strip()
            if s.startswith("# ") and s.lower().startswith("# mowgo"):
                title = s.lstrip("# ").strip()
                break
    if not title:
        # fall back to first non-preamble line
        for ln in first_content["content"].splitlines():
            s = ln.strip()
            if s and not s.startswith("Cronjob Response") and "job_id" not in s and s != "-------------":
                title = s[:110]
                break
    if not title:
        title = first_content["content"].replace("\n", " ")[:110]
    lines.append(f"### {ts_label} — {auth}: {title}")
    lines.append(f"**{auth}** —")
    lines.append("")
    for g in group:
        lines.append(g["content"])
        lines.append("")
    lines.append("---")
    lines.append("")
    i = j

lines.append("")
lines.append(f"*Raw dump generated by MowGo nightly vault sync — 2026-08-09 02:00 UTC*")
lines.append("")

with open(OUT, "w") as f:
    f.write("\n".join(lines))

print(f"Wrote {OUT}: {len(new)} new messages ({len(content_new)} content + {len(footer_new)} footer-only), {len(lines)} lines")
