import { useEffect, useRef, useState } from 'react';
import { ArrowRight, DollarSign, Sprout } from 'lucide-react';
import { Link } from 'react-router-dom';
import usePageTitle from '../hooks/usePageTitle';

const rows = [
  ['Yardbook', 'Free', 'Scheduling, invoicing, basic routing, lot measurement', 'Ads in the interface, payment surcharge, per-user pricing once you pay'],
  ['MowGo', 'Free tier, then $39 flat', 'Unlimited clients, recurring jobs, route optimization, invoicing, offline mode', 'Newer platform, smaller ecosystem'],
  ['QuoteIQ', '$29.99', 'Scheduling calendar, estimating, invoicing', 'Route optimization and self-booking locked behind $299 Elite tier'],
  ['Jobber', '$39', 'Scheduling, clients, invoicing', '$29 per extra user; real features climb into $119-$199 tiers'],
  ['Service Autopilot', '$49 + sign-up fee', 'Scheduling, CRM', 'Routing is a paid add-on; full stack lands around $715/mo'],
  ['RealGreen', 'Quote only, est. $199+', 'Program scheduling for fert/chemical ops', 'Enterprise tool, demo-gated, overkill for mowing'],
  ['LMN', 'Quote only, est. $99-$598', 'Crew scheduling, timesheets, job costing', 'Budget-first workflow; built for commercial contracts'],
];

function FadeIn({ children, className = '', delay = 0 }) {
  const ref = useRef(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { setVisible(true); obs.disconnect(); } }, { threshold: 0.1 });
    obs.observe(el);
    return () => obs.disconnect();
  }, []);
  return <div ref={ref} className={`transition-all duration-700 ease-out ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-6'} ${className}`} style={{ transitionDelay: `${delay}ms` }}>{children}</div>;
}

const heading = 'text-2xl md:text-3xl font-extrabold text-gray-900 dark:text-white tracking-tight mb-6';
const prose = 'space-y-4 text-gray-600 dark:text-gray-400 leading-relaxed';

export default function LawnCareSoftwareCost() {
  usePageTitle('How Much Does Lawn Care Software Cost in 2026? | MowGo', 'Lawn care software pricing in 2026: what Jobber, QuoteIQ, Yardbook, Service Autopilot and MowGo actually cost, the per-user pricing trap, and the flat-priced alternative.');
  return <div className="min-h-screen bg-white dark:bg-gray-950 selection:bg-emerald-200 dark:selection:bg-emerald-800">
    <nav className="sticky top-0 z-50 bg-white/80 dark:bg-gray-950/80 backdrop-blur-md border-b border-gray-100 dark:border-gray-800"><div className="max-w-4xl mx-auto px-4 h-14 flex items-center justify-between">
      <Link to="/" className="flex items-center gap-2.5 text-gray-900 dark:text-white font-bold text-lg min-h-[44px]"><span className="w-7 h-7 rounded-lg bg-gradient-to-br from-emerald-400 to-emerald-600 flex items-center justify-center"><Sprout className="w-4 h-4 text-white" /></span>MowGo</Link>
      <div className="flex items-center gap-2"><Link to="/compare" className="text-sm font-medium text-gray-500 dark:text-gray-400 hover:text-emerald-600 px-3 py-2 min-h-[44px] inline-flex items-center">Compare</Link><Link to="/login" className="text-sm font-semibold text-gray-600 dark:text-gray-400 hover:text-emerald-600 px-4 py-2 min-h-[44px] inline-flex items-center">Log In</Link></div>
    </div></nav>
    <section className="relative overflow-hidden"><div className="absolute inset-0 bg-gradient-to-br from-emerald-50 via-white to-green-50 dark:from-gray-900 dark:via-gray-950 dark:to-emerald-950" /><FadeIn className="relative max-w-3xl mx-auto px-4 pt-16 pb-14 md:pt-24 md:pb-20 text-center">
      <div className="inline-flex items-center gap-2 bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-300 rounded-full px-4 py-1.5 text-sm font-medium mb-6"><DollarSign className="w-4 h-4" />2026 pricing guide</div>
      <h1 className="text-3xl sm:text-4xl md:text-5xl font-extrabold text-gray-900 dark:text-white tracking-tight leading-[1.1]">How Much Does Lawn Care Software Cost in 2026?</h1>
      <p className="mt-6 text-lg text-gray-500 dark:text-gray-400 max-w-2xl mx-auto leading-relaxed italic">A plain-English breakdown of what lawn care software actually costs, what sneaks the bill up, and where the cheap option is genuinely good. Prices verified against vendor pricing pages, August 2026.</p>
      <div className="mt-8 flex flex-col sm:flex-row gap-3 justify-center"><Link to="/login?mode=signup" className="group inline-flex justify-center items-center gap-2 bg-emerald-600 text-white font-bold rounded-xl px-8 py-3.5 hover:bg-emerald-700">Start Free <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" /></Link><Link to="/compare" className="inline-flex justify-center items-center bg-white dark:bg-gray-900 text-gray-700 dark:text-gray-200 font-semibold rounded-xl px-8 py-3.5 border border-gray-200 dark:border-gray-700">Compare Platforms</Link></div>
    </FadeIn></section>
    <article className="max-w-3xl mx-auto px-4 py-12 space-y-16">
      <FadeIn><div className={prose}><p>If you run a lawn care business, you've probably typed "lawn care software pricing" into Google and come out more confused than you went in. Every vendor says they're the affordable option. Most of them are quoting you a price that covers one person, one feature, and none of the stuff you actually need.</p><p>Here's the honest state of pricing in 2026, what the real numbers are, and where the traps are.</p></div></FadeIn>
      <FadeIn><section><h2 className={heading}>The real price range</h2><div className={`${prose} mb-6`}><p>Lawn care software runs from $0 to $700+ a month. Most of that range is wasted money for a small crew.</p><p>The actual options:</p></div><div className="overflow-x-auto"><div className="card overflow-hidden min-w-[760px]"><table className="w-full text-sm"><thead><tr className="bg-gray-50 dark:bg-gray-900">{['Platform', 'Starting price', 'What you get at that price', 'The catch'].map(x => <th key={x} className="text-left px-4 py-3 text-gray-600 dark:text-gray-300">{x}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row[0]} className={`border-t border-gray-100 dark:border-gray-800 ${row[0] === 'MowGo' ? 'bg-emerald-50 dark:bg-emerald-950/30' : ''}`}>{row.map((x, i) => <td key={x} className={`px-4 py-3 align-top text-gray-600 dark:text-gray-400 ${i === 0 ? 'font-semibold text-gray-900 dark:text-white' : ''}`}>{x}</td>)}</tr>)}</tbody></table></div></div><p className="mt-6 text-gray-600 dark:text-gray-400 leading-relaxed">A typical 5 to 10 person lawn business should expect to pay $150 to $350 a month on a full-featured platform. A solo or two-person crew does not need to pay that.</p></section></FadeIn>
      <FadeIn><section><h2 className={heading}>The trap: per-user pricing</h2><div className={prose}><p>This is the one that quietly bleeds lawn care businesses dry, because lawn care scales by adding crew, and per-user software scales your bill right along with them.</p><p>Jobber's math is the clearest example. Core starts at $39 a month for one user. Add a helper and you jump to Team Connect at $169 a month for five users. That's not a $29 fee. That's a $130 jump the day you hire your first crew member.</p><p>Grow your crew to seven people and you're looking at $349 a month on Team Grow, plus $29 per seat beyond the cap. Then the add-ons start: AI Receptionist at $99, Marketing Suite at $79.</p><p>A lawn company with three trucks on Jobber can easily spend more than $400 a month before they've bought anything that optimizes a route.</p><div className="card p-6 border-emerald-200 dark:border-emerald-800 bg-emerald-50/70 dark:bg-emerald-950/20 grid sm:grid-cols-2 gap-5 text-center"><div><strong className="text-emerald-700 dark:text-emerald-300">MowGo</strong><div className="text-4xl font-extrabold text-gray-900 dark:text-white">$39</div>flat</div><div><strong className="text-amber-700 dark:text-amber-300">Jobber</strong><div className="text-4xl font-extrabold text-gray-900 dark:text-white">$169</div>team plan</div></div><p>Compare that to flat pricing. MowGo charges $39 flat for a solo owner with unlimited clients and jobs. Crew tier is $79 a month and that includes the owner plus one crew member; every extra crew member is $10. A five-person crew on MowGo pays $109 a month total. The same crew on Jobber pays $169 on the cheapest team plan, before add-ons.</p><p>That's the difference between software that grows with you and software that taxes every hire you make.</p></div></section></FadeIn>
      <FadeIn><section><h2 className={heading}>What actually matters more than price</h2><div className={prose}><p>Price is the number you compare. It is not the number that decides whether the software pays for itself. That's crew-hours.</p><div className="card p-6 border-amber-200 dark:border-amber-800 bg-amber-50/50 dark:bg-amber-950/20">A two-person crew losing 40 minutes a day to a bad route, at $35 an hour loaded labor cost per man, burns roughly $47 a day. That's about $565 a month. Route optimization that claws back even half of that pays for the software before you count a single new job.</div><p>The same 40 reclaimed minutes is about one extra $55 mow per day. That's $1,320 a month in found revenue on the same payroll. Software doesn't cut grass. It decides how many lawns the same two people can cut.</p><p>So the real question for any platform is not "what does it cost per month" but "does it put the next recurring visit on the calendar automatically, and does it keep Tuesday's stops in the same part of town?" Everything else is decoration.</p></div></section></FadeIn>
      <FadeIn><section><h2 className={heading}>The free tier, honestly</h2><div className={prose}><p>Yardbook's free tier is genuinely free and genuinely useful. If you're a brand-new solo with ten lawns and a borrowed trailer, that's where you should start. The ads and the payment surcharge are a fair trade at that stage.</p><p>The problem comes when you grow. Yardbook's paid plans are $34.99 per user per month on Business and $49.99 per user on Enterprise. A seven-person team pays $245 to $350 a month for software that was free six months earlier. Same per-user trap, just delayed.</p><div className="grid sm:grid-cols-2 gap-4"><div className="card p-5"><strong className="text-gray-900 dark:text-white">Yardbook</strong><p>Free to start; $34.99–$49.99 per user when you grow.</p></div><div className="card p-5 bg-emerald-50 dark:bg-emerald-950/20 border-emerald-200"><strong className="text-emerald-700 dark:text-emerald-300">MowGo</strong><p>Five clients free forever; then $39 flat.</p></div></div><p>MowGo's free tier is different in one respect: it's capped by clients, not by time. Five clients free, forever, no card, no trial clock. When you outgrow it, the paid plan is $39 flat, not $34.99 per person.</p></div></section></FadeIn>
      <FadeIn><section><h2 className={heading}>What you should actually do</h2><ol className="space-y-4">{["If you're a solo with a small book and you don't want to pay anything, use the free tier of something. Yardbook or MowGo. Learn the habits, build the book.", "If you're hiring your first crew member this season, do the per-user math before you sign anything. A $39 plan plus one $10 crew seat beats a $169 team plan that does the same thing.", "If you're running 300+ recurring accounts with office staff, Service Autopilot's automation engine is worth its price and its setup time. That's the one case where the heavy tool earns its keep.", "If you run chemical applications across multiple crews, RealGreen is the industry standard for a reason. If you mow, it's a freight train for a grocery run."].map((x, i) => <li key={x} className="card p-5 flex gap-4 text-gray-600 dark:text-gray-400 leading-relaxed"><span className="w-8 h-8 flex-shrink-0 rounded-full bg-emerald-600 text-white font-bold flex items-center justify-center">{i + 1}</span>{x}</li>)}</ol><p className="mt-6 text-gray-600 dark:text-gray-400 leading-relaxed">The software that wins is the one that survives the season. The one that charges you more every time you hire is not that.</p></section></FadeIn>
      <FadeIn><section className="relative overflow-hidden rounded-2xl"><div className="absolute inset-0 bg-gradient-to-br from-emerald-500 via-green-600 to-green-700" /><div className="relative px-8 py-12 text-center"><h2 className="text-3xl font-extrabold text-white mb-4">Try MowGo Free</h2><p className="text-emerald-100 mb-8">Five clients free, forever. No card and no trial clock.</p><Link to="/login?mode=signup" className="group inline-flex items-center gap-2 bg-white text-emerald-600 font-bold rounded-xl px-8 py-3.5">Start Free <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" /></Link></div></section></FadeIn>
    </article>
    <footer className="bg-gray-50 dark:bg-gray-900 border-t border-gray-100 dark:border-gray-800"><div className="max-w-4xl mx-auto px-4 py-8 flex flex-col sm:flex-row justify-between items-center gap-4"><div className="flex items-center gap-2.5 text-gray-400 text-sm"><span className="w-6 h-6 rounded-md bg-gradient-to-br from-emerald-400 to-emerald-600 flex items-center justify-center"><Sprout className="w-3.5 h-3.5 text-white" /></span>MowGo &copy; 2026</div><div className="flex gap-5 text-sm text-gray-500"><Link to="/compare">Compare</Link><Link to="/route-audit">Route audit</Link><Link to="/switch-from-lawnpro">Switch from LawnPro</Link></div></div></footer>
  </div>;
}
