#!/usr/bin/env python3
"""Generate raw channel dump markdown files for the nightly vault sync.

Usage:
  python3 gen_raw_dumps.py --src <persisted tool-output json> \
      --cutoff 2026-08-01T02:00:00Z --sync-ts "2026-08-02 02:00 UTC"

The SRC file is the persisted output of the discord fetch_messages tool call
(saved under /tmp/hermes-results/). TITLES maps new-message ids to display
titles; a title of None skips the message (footer-only trailer).
"""
import argparse
import datetime
import json
import re


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument('--src', required=True)
    p.add_argument('--cutoff', required=True, help='ISO UTC cutoff for "new" messages')
    p.add_argument('--sync-ts', required=True, help='Display timestamp, e.g. 2026-08-02 02:00 UTC')
    return p.parse_args()


def clean(content: str) -> str:
    """Strip cron boilerplate from message content."""
    lines = content.split('\n')
    out = []
    for ln in lines:
        s = ln.strip()
        if s.startswith('Cronjob Response:'):
            continue
        if s.startswith('(job_id:'):
            continue
        if s == '-------------' or s == '---':
            continue
        if re.match(r'^To stop or manage this job.*$', s):
            continue
        out.append(ln)
    text = '\n'.join(out)
    # collapse 3+ blank lines
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()


def ts_parts(m):
    ts = datetime.datetime.fromisoformat(m['timestamp'])
    return f"{ts.strftime('%b %d')}, {ts.strftime('%H:%M')}", ts.strftime('%b %d %H:%M')


def title_for(m, titles):
    t = titles.get(m['id'])
    if t:
        return t
    content = m['content']
    for ln in content.split('\n'):
        s = ln.strip()
        if s.startswith('# '):
            return s[2:].strip()
    for ln in content.split('\n'):
        s = ln.strip()
        if s and not s.startswith(('Cronjob', '(job_id', '-', 'To stop', '|')):
            return s[:90]
    return '(no title)'


def main():
    args = parse_args()
    with open(args.src) as f:
        data = json.load(f)

    cutoff = datetime.datetime.fromisoformat(args.cutoff)
    msgs = sorted(data['messages'], key=lambda m: m['timestamp'])
    new = [m for m in msgs if datetime.datetime.fromisoformat(m['timestamp']) >= cutoff]
    old = [m for m in msgs if datetime.datetime.fromisoformat(m['timestamp']) < cutoff]
    sync_date = args.sync_ts[:10]

    # Titles for new messages (update per run). None = footer-only trailer, skip.
    TITLES = {
        '1534755028945076414': 'Intel Engine — Pricing (02:48 UTC)',
        '1534755029670428794': 'Intel Engine — Pricing (2/2)',
        '1534820161326944386': 'Intel Engine — Features (07:07 UTC)',
        '1534820162396749885': 'Intel Engine — Features (2/2)',
        '1534851543029907456': 'Stripe Health Check (1/2)',
        '1534851544867143791': 'Stripe Health Check (2/2)',
        '1534883550011195392': 'Intel Engine — Competitor (11:19 UTC)',
        '1534883551319691365': 'Intel Engine — Competitor (2/2)',
        '1534901360246653052': 'Invoice Reminders (12:30 UTC)',
        '1534948443464794162': 'Intel Engine — Daily Summary (15:19 UTC)',
        '1535013432657707138': 'Intel Engine — Pricing (19:37 UTC)',
        '1535087415163879515': 'Intel Engine — Features (23:55 UTC)',
        '1535087416140890132': 'Intel Engine — Features (2/2)',
    }

    shown = [m for m in new if TITLES.get(m['id']) is not None]
    skipped = len(new) - len(shown)

    # ---------- mowgo channel ----------
    hdr = f"""# 🌱 mowgo — Raw Channel Dump
**{args.sync_ts} | {len(msgs)} messages fetched ({len(new)} new since last sync; {len(shown)} with content{f' + {skipped} footer-only trailer' if skipped else ''})**

## Most Recent Activity (New since {cutoff.strftime('%b %d %H:%M')} UTC sync)

"""
    entries = []
    for m in shown:
        label, _ = ts_parts(m)
        entries.append(f"### {label} — {title_for(m, TITLES)}\n**{m['author']['username']}** —\n\n{clean(m['content'])}\n")
    body = hdr + '\n'.join(entries)

    # Prior activity summary (grouped by date, brief)
    body += "\n## Prior Activity (unchanged from earlier syncs — summary)\n\n"
    by_date = {}
    for m in old:
        d = datetime.datetime.fromisoformat(m['timestamp']).strftime('%b %d')
        by_date.setdefault(d, []).append(m)

    for d in sorted(by_date.keys(), reverse=True):
        group = by_date[d]
        lines = [f"### {d} — {len(group)} messages (already captured in prior syncs)"]
        for m in group:
            t = datetime.datetime.fromisoformat(m['timestamp']).strftime('%H:%M')
            first = clean(m['content']).split('\n')[0][:110]
            lines.append(f"**{m['author']['username']}** {t} — {first}")
        body += '\n'.join(lines) + '\n\n'

    body += f"""---
*Raw dump generated by MowGo nightly vault sync — {args.sync_ts}*
"""
    out_mowgo = f'/opt/data/mowgo/vault/{sync_date}_channel-mowgo-raw.md'
    with open(out_mowgo, 'w') as f:
        f.write(body)
    print('mowgo raw written:', out_mowgo, len(body), 'chars')

    # ---------- outreach + cowork ----------
    # NOTE (2026-08-07): #🌱mowgo-outreach returns 404 Unknown Channel —
    # the channel no longer exists (verified on two fetches this run).
    outreach = f"""# 🌱 mowgo-outreach — Raw Channel Dump
**{args.sync_ts} | ⚠️ CHANNEL GONE — fetch returned 404 Unknown Channel (2×)**

The outreach channel (`1529711006023024680`) **no longer exists** as of this sync
(was reachable at the Aug 6 12:00Z scan; 404 verified on two fetches Aug 7 02:00Z).
Likely deleted/renamed-away by Aaron. **0 messages synced this run.**

Last known state (from the 2026-08-06 sync): 55 messages fetched, newest Aug 5
01:48Z (wave-1 SMS scripts for 21 leads); the 12-message duplicate batch was
cleaned Aug 5; the Rule of 100 cron stopped delivering here Aug 5 15:11Z
(moved to #🌱mowgo-leads), so no active delivery targets a dead channel.

**Action:** confirm the deletion was intentional; update vault index +
daily_scan channel lists accordingly.

---
*Raw dump generated by MowGo nightly vault sync — {args.sync_ts}*

"""
    out_outreach = f'/opt/data/mowgo/vault/{sync_date}_channel-outreach-raw.md'
    with open(out_outreach, 'w') as f:
        f.write(outreach)

    cowork = f"""# 🤝 mowgo-cowork — Raw Channel Dump
**{args.sync_ts} | 0 messages (0 new since last sync)**

Channel is empty — **cleaned Aug 6 13:30Z** (128 watchdog-failure spam messages
deleted by the 8am action; see `2026-08-06_daily-sync.md`). Watchdog has held
with 0 new failures since Aug 4 13:50Z. No coworking sessions have taken place.

---
*Raw dump generated by MowGo nightly vault sync — {args.sync_ts}*

"""
    out_cowork = f'/opt/data/mowgo/vault/{sync_date}_channel-cowork-raw.md'
    with open(out_cowork, 'w') as f:
        f.write(cowork)

    print('outreach + cowork written:', out_outreach, out_cowork)


if __name__ == '__main__':
    main()
