#!/usr/bin/env python3
"""Generate raw channel dump markdown files for the nightly vault sync."""
import json
import datetime
import re

SRC = '/tmp/hermes-results/call_00_lzl1dovwPa12er2B6dNG8192.txt'
CUTOFF = datetime.datetime(2026, 7, 31, 2, 0, 0, tzinfo=datetime.timezone.utc)
SYNC_TS = '2026-08-01 02:00 UTC'

with open(SRC) as f:
    data = json.load(f)

msgs = sorted(data['messages'], key=lambda m: m['timestamp'])
new = [m for m in msgs if datetime.datetime.fromisoformat(m['timestamp']) >= CUTOFF]
old = [m for m in msgs if datetime.datetime.fromisoformat(m['timestamp']) < CUTOFF]

def clean(content: str) -> str:
    """Strip cron boilerplate from message content."""
    lines = content.split('\n')
    out = []
    for ln in lines:
        s = ln.strip()
        if s.startswith('Cronjob Response:'):
            continue
        if s.startswith('(job_id:'):
            continue
        if s == '-------------' or s == '---':
            continue
        if re.match(r'^To stop or manage this job.*$', s):
            continue
        out.append(ln)
    text = '\n'.join(out)
    # collapse 3+ blank lines
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()

TITLES = {
    '1532586808414830662': 'Intel Engine — Feature Ideas (Run 02:57 UTC)',
    '1532586809639567400': 'Intel Engine — Feature Ideas (2/2)',
    '1532648334903349399': 'Intel Engine — Competitor Monitoring (Run 07:13 UTC)',
    '1532648338061525066': 'Intel Engine — Competitor Monitoring (2/2)',
    '1532677432451010681': 'Stripe Health Check (1/3)',
    '1532677433772347402': 'Stripe Health Check (2/3)',
    '1532677434602684467': 'Stripe Health Check (3/3)',
    '1532709395543232602': 'Intel Engine — Industry Trends (Run 11:17 UTC)',
    '1532709396117852253': 'Intel Engine — Industry Trends (2/2)',
    '1532771007373377546': 'Intel Engine — Pricing Intelligence (Run 4, 15:20 UTC)',
    '1532771008262438933': None,  # footer-only trailer, skip
    '1532832051126997186': 'Intel Engine — Feature Ideas (Run 5, Evening 19:24 UTC)',
    '1532832052213321771': 'Intel Engine — Feature Ideas (2/2)',
    '1532894478350811206': 'Intel Engine — Competitor Monitoring (Run 6, Night 23:28 UTC)',
    '1532894478958858332': 'Intel Engine — Competitor Monitoring (2/2)',
}

def title_for(m) -> str:
    t = TITLES.get(m['id'])
    if t:
        return t
    content = m['content']
    for ln in content.split('\n'):
        s = ln.strip()
        if s.startswith('# '):
            return s[2:].strip()
    for ln in content.split('\n'):
        s = ln.strip()
        if s and not s.startswith(('Cronjob', '(job_id', '-', 'To stop', '|')):
            return s[:90]
    return '(no title)'

def ts_parts(m):
    ts = datetime.datetime.fromisoformat(m['timestamp'])
    return f"{ts.strftime('%b %d')}, {ts.strftime('%H:%M')}", ts.strftime('%b %d %H:%M')

# ---------- mowgo channel ----------
hdr = f"""# 🌱 mowgo — Raw Channel Dump
**{SYNC_TS} | {len(msgs)} messages fetched ({len(new)} new since last sync; 14 with content + 1 footer-only trailer)**

## Most Recent Activity (New since Jul 31 02:00 UTC sync)

"""
entries = []
for m in new:
    if TITLES.get(m['id']) is None:
        continue  # footer-only trailer message
    label, _ = ts_parts(m)
    entries.append(f"### {label} — {title_for(m)}\n**{m['author']['username']}** —\n\n{clean(m['content'])}\n")
body = hdr + '\n'.join(entries)

# Prior activity summary (grouped by date, brief)
body += "\n## Prior Activity (unchanged from earlier syncs — summary)\n\n"
by_date = {}
for m in old:
    d = datetime.datetime.fromisoformat(m['timestamp']).strftime('%b %d')
    by_date.setdefault(d, []).append(m)

for d in sorted(by_date.keys(), reverse=True):
    group = by_date[d]
    lines = [f"### {d} — {len(group)} messages (already captured in prior syncs)"]
    for m in group:
        t = datetime.datetime.fromisoformat(m['timestamp']).strftime('%H:%M')
        first = clean(m['content']).split('\n')[0][:110]
        lines.append(f"**{m['author']['username']}** {t} — {first}")
    body += '\n'.join(lines) + '\n\n'

body += f"""---
*Raw dump generated by MowGo nightly vault sync — {SYNC_TS}*
"""
with open('/opt/data/mowgo/vault/2026-08-01_channel-mowgo-raw.md', 'w') as f:
    f.write(body)
print('mowgo raw written:', len(body), 'chars')

# ---------- outreach + cowork (unchanged) ----------
outreach = f"""# 🌱 mowgo-outreach — Raw Channel Dump
**{SYNC_TS} | 23 messages (0 new since last sync)**

No new messages since Jul 26, 14:12 UTC. Outreach channel remains dormant.

## Most Recent Activity (from prior sync — unchanged)

### Jul 26, 14:12 — Reddit Monitor Summary
**HeremesV2** — 8 threads found (6 high, 2 medium priority). Templates A-F for engagement across r/LawnCarePros, r/CRM, r/lawncare, r/sweatystartup.

### Jul 26, 14:12 — Reddit Monitor (Threads 7-8)
**HeremesV2** — r/lawncare "Need advice on tools and software" (Template A), r/sweatystartup "Evaluate 6 figure landscaping plan" (Template E)

### Jul 26, 14:12 — Reddit Monitor (Threads 4-6)
**HeremesV2** — r/LawnCarePros "Current state of lawn care" (Template D), r/CRM "Best CRM for lawn care 2026" (Template A), r/sweatystartup "Scheduling lawn care customers" (Template C)

### Jul 26, 14:12 — Reddit Monitor (Threads 1-3)
**HeremesV2** — r/LawnCarePros "App features" (Template A), r/LawnCarePros "Best practices for customer payment" (Template C), r/LawnCarePros "New business" (Template B)

### Jul 25, 14:11 — Reddit Monitor Summary
**HeremesV2** — 10 threads across r/LawnCarePros, r/landscaping, r/sweatystartup

### Jul 24, 15:02 — Daily Outreach Actions
**HeremesV2** — Top 3 Reddit replies + cold outreach kickoff (3 leads: Mowzilla, Walter's, Aaron's) + Facebook engagement

### Jul 24, 14:07 — Reddit Monitor Summary
**HeremesV2** — 5 threads found (2 high, 3 medium). Reddit blocks all scraping (403).

### Jul 23, 15:02 — Daily Outreach Actions
**HeremesV2** — 3 Reddit replies queued + Facebook engagement plan

### Jul 23, 14:07 — Reddit Monitor Summary
**HeremesV2** — 4 threads found incl. GOLDEN r/landscaping "1-3 person crews" thread. All Reddit access 403-blocked.

### Jul 23, 04:48 — MowFlow Outreach System Setup
**HeremesV2** — Outreach system status: Reddit Monitor (daily 9am CST) + Daily Actions (10am CST weekdays). System files: facebook-groups.md, reply-templates.md, lead-tracker.md, reddit-monitor.md. First move: 6 warm leads via text/DM.

---
*Raw dump generated by MowGo nightly vault sync — {SYNC_TS}*
"""
with open('/opt/data/mowgo/vault/2026-08-01_channel-outreach-raw.md', 'w') as f:
    f.write(outreach)

cowork = f"""# 🤝 mowgo-cowork — Raw Channel Dump
**{SYNC_TS} | 0 messages (0 new since last sync)**

This channel remains empty. No coworking sessions have taken place yet.

---
*Raw dump generated by MowGo nightly vault sync — {SYNC_TS}*
"""
with open('/opt/data/mowgo/vault/2026-08-01_channel-cowork-raw.md', 'w') as f:
    f.write(cowork)

print('outreach + cowork written')
